name = "itec-cors-proxy"
main = "src/index.js"
compatibility_date = "2024-12-04"

# Uncomment to use a custom domain
# routes = [
#   { pattern = "api.yourdomain.com", custom_domain = true }
# ]

[vars]
ALLOWED_ORIGIN = "https://adielbm.github.io"
TARGET_BASE_URL = "https://center.tennis.org.il"
